FROM nginx:1.27-alpine

# Supprimer la config par défaut de Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copier la configuration personnalisée (reverse-proxy vers backend:8000 et frontend:3000)
COPY Dockerfile.nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
